# Generated by Django 5.2.1 on 2025-09-03 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.PositiveSmallIntegerField(help_text='Percentage weight in final score (e.g., 40 for CA, 60 for Exam)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_score', models.PositiveSmallIntegerField(default=100, help_text='Maximum raw score for this exam type (e.g., 40 for CA, 60 for Exam)')),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='PredefinedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('teacher', 'Class Teacher Comment'), ('principal', 'Principal Comment')], max_length=10)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('teacher', 'Class Teacher Comment'), ('principal', 'Principal Comment')], max_length=10)),
                ('comment', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Raw score (e.g., out of 40 for CA, 60 for Exam)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_recorded', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['exam_type__weight'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
                ('level', models.PositiveSmallIntegerField()),
                ('arm', models.CharField(blank=True, choices=[('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Gamma', 'Gamma'), ('Delta', 'Delta')], default='Alpha', max_length=20, null=True)),
            ],
            options={
                'ordering': ['level', 'arm'],
                'unique_together': {('level', 'arm')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
            ],
        ),
    ]
