# Generated by Django 5.2.1 on 2025-09-03 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('admission_date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='students/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('height', models.DecimalField(decimal_places=1, help_text='Height in cm', max_digits=4)),
                ('weight', models.DecimalField(decimal_places=1, help_text='Weight in kg', max_digits=4)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('diagnosed_date', models.DateField()),
                ('treatment', models.TextField(blank=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('participation', models.PositiveSmallIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], help_text='Class engagement, teamwork')),
                ('responsibility', models.PositiveSmallIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], help_text='Completing assignments, following rules')),
                ('creativity', models.PositiveSmallIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], help_text='Thinking skills, innovation')),
                ('cooperation', models.PositiveSmallIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Developing'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], help_text='Social skills, respect for others')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-term__start_date'],
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
